#!/usr/bin/env python3
"""Build the subset font bundle for the dynamic Kaomoji Maker OG card.

The maker can only emit glyphs from the curated galleries (src/data/galleries.js),
a bounded ~136-codepoint set spanning ~8 scripts. This subsets just those glyphs
out of the system Noto families and emits functions/og/_fonts.js (base64 font
buffers) so the OG Pages Function can rasterise any creation at the edge with a
tiny (~60 KB) font payload instead of multi-megabyte whole fonts.

Run manually when the galleries change (not in the pre-commit hook — it needs
Python + fonttools + system Noto fonts):  python3 scripts/build-og-fonts.py
Commit the regenerated functions/og/_fonts.js.
"""
import base64, glob, json, subprocess, sys, os
from fontTools.ttLib import TTFont, TTCollection
from fontTools.subset import Subsetter, Options

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

# Codepoints the maker can emit — galleries.js is the single source of truth.
js = """
import('./src/data/galleries.js').then(m => {
  const cps = new Set();
  for (const opts of Object.values(m.galleries)) for (const e of opts) {
    if (!e) continue;
    const parts = e.glyph != null ? [e.glyph] : [e.left, e.right];
    for (const p of parts) for (const ch of p) cps.add(ch.codePointAt(0));
  }
  console.log(JSON.stringify([...cps]));
});
"""
cps = set(json.loads(subprocess.check_output(["node", "--input-type=module", "-e", js])))
# Plus the card's wordmark + ASCII.
for ch in "kaomoji.fyi · make your own —":
    cps.add(ord(ch))
cps = sorted(cps)

# Catalogue system Noto faces, preferring Sans + Regular + non-CJK (smaller).
def weight_rank(p):
    name = p.lower()
    return (0 if "-regular" in name or "regular" in name else 1,
            0 if "sans" in name else 1,
            1 if "cjk" in name else 0,
            2 if "serif" in name else 0)

faces = []
for pat in ["/usr/share/fonts/noto/*.tt[cf]", "/usr/share/fonts/noto-cjk/*.tt[cf]", "/usr/share/fonts/**/Noto*.tt[cf]"]:
    for p in glob.glob(pat, recursive=True):
        try:
            fonts = TTCollection(p).fonts if p.endswith(".ttc") else [TTFont(p)]
        except Exception:
            continue
        for i, ft in enumerate(fonts):
            try:
                cm = set(ft.getBestCmap().keys())
            except Exception:
                continue
            faces.append((p, i, cm))
faces.sort(key=lambda f: weight_rank(f[0]))

# Greedy set cover: fewest faces, preferring the better-ranked ones on ties.
need = set(c for c in cps if c > 0x20)
chosen = []
while need:
    best, best_cov = None, 0
    for f in faces:
        cov = len(need & f[2])
        if cov > best_cov:
            best, best_cov = f, cov
    if not best:
        break
    chosen.append(best)
    need -= best[2]
if need:
    print("WARNING: uncoverable codepoints:", sorted(hex(c) for c in need), file=sys.stderr)

# Subset each chosen face to the target set and base64-encode.
buffers, total = [], 0
opt = Options()
opt.set(layout_features=[], notdef_outline=True, recalc_bounds=False,
        drop_tables=["GSUB", "GPOS", "GDEF", "BASE", "JSTF", "DSIG"])
for p, i, _cm in chosen:
    ft = TTCollection(p).fonts[i] if p.endswith(".ttc") else TTFont(p)
    ss = Subsetter(options=opt)
    ss.populate(unicodes=cps)
    ss.subset(ft)
    tmp = "/tmp/_og_subset.ttf"
    ft.save(tmp)
    data = open(tmp, "rb").read()
    total += len(data)
    buffers.append(base64.b64encode(data).decode("ascii"))
    print("  %-48s %6d bytes" % (os.path.basename(p), len(data)))
os.path.exists("/tmp/_og_subset.ttf") and os.remove("/tmp/_og_subset.ttf")

out = ("// AUTO-GENERATED by scripts/build-og-fonts.py — do not edit by hand.\n"
       "// Base64 subset Noto fonts covering exactly the Kaomoji Maker's glyphs,\n"
       "// for the dynamic OG card (functions/og/maker.js). Regenerate when the\n"
       "// galleries change:  python3 scripts/build-og-fonts.py\n\n"
       "export const fontsB64 = [\n" + "".join('  "%s",\n' % b for b in buffers) + "];\n")
os.makedirs("functions/og", exist_ok=True)
open("functions/og/_fonts.js", "w").write(out)
print("Wrote functions/og/_fonts.js — %d fonts, %d bytes (~%d KB) total, %d codepoints"
      % (len(buffers), total, total // 1024, len(cps)))
